#!/bin/bash

set -e
echo -e "Installing R packages...\n"

R -e "install.packages('remotes', repos='https://cloud.r-project.org/')"

# Neccesary to prevent error 503 (https://shinyproxy.io/faq/#the-assets-of-my-shiny-app-sometimes-fail-to-load-http-error-503)
R -e "remotes::install_version(c('withr'), version = '2.5.0', repos='https://cloud.r-project.org/')"
R -e "withr::with_makevars(c(PKG_CPPFLAGS='-DHTTP_MAX_HEADER_SIZE=0x7fffffff'), {remotes::install_version(c('shiny'), version = '1.7.4', repos='https://cloud.r-project.org/')}, assignment = '+=')"

R -e "remotes::install_version('blastula', version = '0.3.5', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('bookdown', version = '0.39', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('bslib', version = '0.7.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('bsplus', version = '0.1.4', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('DBI', version = '1.2.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('DT', version = '0.33', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('flexdashboard', version = '0.6.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('fontawesome', version = '0.5.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('formattable', version = '0.2.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('gganimate', version = '1.0.9', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('ggrepel', version = '0.9.5', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('highcharter', version = '0.9.4', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('leaflet', version = '2.2.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('kableExtra', version = '1.4.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('openxlsx', version = '4.2.5.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('patchwork', version = '1.2.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('plyr', version = '1.8.9', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('rapidjsonr', version = '1.2.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('rhandsontable', version = '0.3.8', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('rmapshaper', version = '0.5.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('rmarkdown', version = '2.27', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('RMySQL', version = '0.10.27', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('RPostgres', version = '1.4.6', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('RPostgreSQL', version = '0.7-6', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('rprojroot', version = '2.0.4', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('shinyBS', version = '0.61.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('shinydashboard', version = '0.7.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('shinyFeedback', version = '0.4.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('shinyjs', version = '2.1.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('shinyWidgets', version = '0.8.6', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('sodium', version = '1.3.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('slackr', version = '3.3.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('stringr', version = '1.5.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('tidyverse', version = '2.0.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('xgboost', version = '1.7.7.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('prophet', version = '1.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('tidymodels', version = '1.2.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('modeltime', version = '1.2.8', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('timetk', version = '2.9.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('reticulate', version = '1.36.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('plumber', version = '1.2.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('httr2', version = '1.0.1', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('webshot', version = '0.5.5', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('quarto', version = '1.4', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('bsicons', version = '0.1.2', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('odbc', version = '1.5.0', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('pool', version = '1.0.3', repos='https://cloud.r-project.org/')"
R -e "remotes::install_version('duckdb', version = '1.0.0', repos='https://cloud.r-project.org/')"

R -e "remotes::install_github(c('edzer/sfr', 'homerhanumat/shinyCustom'))"
R -e "webshot::install_phantomjs()"

echo -e "R packages installed!\n"